#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 05, 2018 02:37:17 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import dataProcessHelper_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    dataProcessHelper_support.set_Tk_var()
    top = TopLevel (root)
    dataProcessHelper_support.init(root, top)
    root.mainloop()


w = None


def create_TopLevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    dataProcessHelper_support.set_Tk_var()
    top = TopLevel (w)
    dataProcessHelper_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_TopLevel():
    global w
    w.destroy()
    w = None

class TopLevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("800x600+709+170")
        top.title("DATA PROCESS HELPER")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.FrameData = tk.Frame(top)
        self.FrameData.place(relx=0.013, rely=0.017, relheight=0.142
                , relwidth=0.969)
        self.FrameData.configure(relief='groove')
        self.FrameData.configure(borderwidth="2")
        self.FrameData.configure(relief='groove')
        self.FrameData.configure(background="#d9d9d9")
        self.FrameData.configure(highlightbackground="#d9d9d9")
        self.FrameData.configure(highlightcolor="black")
        self.FrameData.configure(width=775)

        self.CopyDataButton = tk.Button(self.FrameData)
        self.CopyDataButton.place(relx=0.013, rely=0.235, height=38, width=99)
        self.CopyDataButton.configure(activebackground="#d9d9d9")
        self.CopyDataButton.configure(activeforeground="#000000")
        self.CopyDataButton.configure(background="#d9d9d9")
        self.CopyDataButton.configure(disabledforeground="#a3a3a3")
        self.CopyDataButton.configure(foreground="#000000")
        self.CopyDataButton.configure(highlightbackground="#d9d9d9")
        self.CopyDataButton.configure(highlightcolor="black")
        self.CopyDataButton.configure(pady="0")
        self.CopyDataButton.configure(text='''复制数据''')
        self.CopyDataButton.bind('<Button-1>',lambda e:dataProcessHelper_support.copy_data(e))

        self.CopyDataFolderText = tk.Text(self.FrameData)
        self.CopyDataFolderText.place(relx=0.155, rely=0.235, relheight=0.494
                , relwidth=0.689)
        self.CopyDataFolderText.configure(background="white")
        self.CopyDataFolderText.configure(font="TkTextFont")
        self.CopyDataFolderText.configure(foreground="black")
        self.CopyDataFolderText.configure(highlightbackground="#d9d9d9")
        self.CopyDataFolderText.configure(highlightcolor="black")
        self.CopyDataFolderText.configure(insertbackground="black")
        self.CopyDataFolderText.configure(selectbackground="#c4c4c4")
        self.CopyDataFolderText.configure(selectforeground="black")
        self.CopyDataFolderText.configure(width=534)
        self.CopyDataFolderText.configure(wrap='word')

        self.FrameProduct = tk.Frame(top)
        self.FrameProduct.place(relx=0.013, rely=0.167, relheight=0.108
                , relwidth=0.969)
        self.FrameProduct.configure(relief='groove')
        self.FrameProduct.configure(borderwidth="2")
        self.FrameProduct.configure(relief='groove')
        self.FrameProduct.configure(background="#d9d9d9")
        self.FrameProduct.configure(highlightbackground="#d9d9d9")
        self.FrameProduct.configure(highlightcolor="black")
        self.FrameProduct.configure(width=775)

        self.RbProduct1 = tk.Radiobutton(self.FrameProduct)
        self.RbProduct1.place(relx=0.026, rely=0.308, relheight=0.415
                , relwidth=0.132)
        self.RbProduct1.configure(activebackground="#d9d9d9")
        self.RbProduct1.configure(activeforeground="#000000")
        self.RbProduct1.configure(background="#d9d9d9")
        self.RbProduct1.configure(disabledforeground="#a3a3a3")
        self.RbProduct1.configure(foreground="#000000")
        self.RbProduct1.configure(highlightbackground="#d9d9d9")
        self.RbProduct1.configure(highlightcolor="black")
        self.RbProduct1.configure(justify='left')
        self.RbProduct1.configure(text='''p1''')
        self.RbProduct1.configure(value="1")
        self.RbProduct1.configure(variable=dataProcessHelper_support.product)


        self.FrameGrr = tk.Frame(top)
        self.FrameGrr.place(relx=0.013, rely=0.383, relheight=0.575
                , relwidth=0.481)
        self.FrameGrr.configure(relief='groove')
        self.FrameGrr.configure(borderwidth="2")
        self.FrameGrr.configure(relief='groove')
        self.FrameGrr.configure(background="#d9d9d9")
        self.FrameGrr.configure(highlightbackground="#d9d9d9")
        self.FrameGrr.configure(highlightcolor="black")
        self.FrameGrr.configure(width=385)

        self.ButtonRunGrr = tk.Button(self.FrameGrr)
        self.ButtonRunGrr.place(relx=0.026, rely=0.029, height=38, width=89)
        self.ButtonRunGrr.configure(activebackground="#d9d9d9")
        self.ButtonRunGrr.configure(activeforeground="#000000")
        self.ButtonRunGrr.configure(background="#d9d9d9")
        self.ButtonRunGrr.configure(disabledforeground="#a3a3a3")
        self.ButtonRunGrr.configure(foreground="#000000")
        self.ButtonRunGrr.configure(highlightbackground="#d9d9d9")
        self.ButtonRunGrr.configure(highlightcolor="black")
        self.ButtonRunGrr.configure(pady="0")
        self.ButtonRunGrr.configure(text='''Grr''')
        self.ButtonRunGrr.bind('<Button-1>',lambda e:dataProcessHelper_support.run_grr(e))

        self.ButtonRunGrrTemplate = tk.Button(self.FrameGrr)
        self.ButtonRunGrrTemplate.place(relx=0.026, rely=0.203, height=38
                , width=89)
        self.ButtonRunGrrTemplate.configure(activebackground="#d9d9d9")
        self.ButtonRunGrrTemplate.configure(activeforeground="#000000")
        self.ButtonRunGrrTemplate.configure(background="#d9d9d9")
        self.ButtonRunGrrTemplate.configure(disabledforeground="#a3a3a3")
        self.ButtonRunGrrTemplate.configure(foreground="#000000")
        self.ButtonRunGrrTemplate.configure(highlightbackground="#d9d9d9")
        self.ButtonRunGrrTemplate.configure(highlightcolor="black")
        self.ButtonRunGrrTemplate.configure(pady="0")
        self.ButtonRunGrrTemplate.configure(text='''GrrTemplate''')
        self.ButtonRunGrrTemplate.bind('<Button-1>',lambda e:dataProcessHelper_support.run_grr_template(e))

        self.TextGRR = tk.Text(self.FrameGrr)
        self.TextGRR.place(relx=0.286, rely=0.029, relheight=0.933
                , relwidth=0.686)
        self.TextGRR.configure(background="white")
        self.TextGRR.configure(font="TkTextFont")
        self.TextGRR.configure(foreground="black")
        self.TextGRR.configure(highlightbackground="#d9d9d9")
        self.TextGRR.configure(highlightcolor="black")
        self.TextGRR.configure(insertbackground="black")
        self.TextGRR.configure(selectbackground="#c4c4c4")
        self.TextGRR.configure(selectforeground="black")
        self.TextGRR.configure(width=264)
        self.TextGRR.configure(wrap='word')

        self.FrameCorr = tk.Frame(top)
        self.FrameCorr.place(relx=0.5, rely=0.383, relheight=0.575
                , relwidth=0.481)
        self.FrameCorr.configure(relief='groove')
        self.FrameCorr.configure(borderwidth="2")
        self.FrameCorr.configure(relief='groove')
        self.FrameCorr.configure(background="#d9d9d9")
        self.FrameCorr.configure(highlightbackground="#d9d9d9")
        self.FrameCorr.configure(highlightcolor="black")
        self.FrameCorr.configure(width=385)

        self.ButtonRunCorr = tk.Button(self.FrameCorr)
        self.ButtonRunCorr.place(relx=0.026, rely=0.029, height=38, width=89)
        self.ButtonRunCorr.configure(activebackground="#d9d9d9")
        self.ButtonRunCorr.configure(activeforeground="#000000")
        self.ButtonRunCorr.configure(background="#d9d9d9")
        self.ButtonRunCorr.configure(disabledforeground="#a3a3a3")
        self.ButtonRunCorr.configure(foreground="#000000")
        self.ButtonRunCorr.configure(highlightbackground="#d9d9d9")
        self.ButtonRunCorr.configure(highlightcolor="black")
        self.ButtonRunCorr.configure(pady="0")
        self.ButtonRunCorr.configure(text='''Corr''')
        self.ButtonRunCorr.bind('<Button-1>',lambda e:dataProcessHelper_support.run_corr(e))

        self.RunCorrCMM = tk.Button(self.FrameCorr)
        self.RunCorrCMM.place(relx=0.026, rely=0.87, height=38, width=89)
        self.RunCorrCMM.configure(activebackground="#d9d9d9")
        self.RunCorrCMM.configure(activeforeground="#000000")
        self.RunCorrCMM.configure(background="#d9d9d9")
        self.RunCorrCMM.configure(disabledforeground="#a3a3a3")
        self.RunCorrCMM.configure(foreground="#000000")
        self.RunCorrCMM.configure(highlightbackground="#d9d9d9")
        self.RunCorrCMM.configure(highlightcolor="black")
        self.RunCorrCMM.configure(pady="0")
        self.RunCorrCMM.configure(text='''CMM''')
        self.RunCorrCMM.bind('<Button-1>',lambda e:dataProcessHelper_support.open_cmm_folder(e))

        self.ButtonRunCorrTemplate = tk.Button(self.FrameCorr)
        self.ButtonRunCorrTemplate.place(relx=0.026, rely=0.754, height=38
                , width=89)
        self.ButtonRunCorrTemplate.configure(activebackground="#d9d9d9")
        self.ButtonRunCorrTemplate.configure(activeforeground="#000000")
        self.ButtonRunCorrTemplate.configure(background="#d9d9d9")
        self.ButtonRunCorrTemplate.configure(disabledforeground="#a3a3a3")
        self.ButtonRunCorrTemplate.configure(foreground="#000000")
        self.ButtonRunCorrTemplate.configure(highlightbackground="#d9d9d9")
        self.ButtonRunCorrTemplate.configure(highlightcolor="black")
        self.ButtonRunCorrTemplate.configure(pady="0")
        self.ButtonRunCorrTemplate.configure(text='''CorrTemplate''')
        self.ButtonRunCorrTemplate.bind('<Button-1>',lambda e:dataProcessHelper_support.run_corr_template(e))

        self.SpinboxCMMCount = tk.Spinbox(self.FrameCorr, from_=1.0, to=30.0)
        self.SpinboxCMMCount.place(relx=0.078, rely=0.638, relheight=0.061
                , relwidth=0.169)
        self.SpinboxCMMCount.configure(activebackground="#f9f9f9")
        self.SpinboxCMMCount.configure(background="white")
        self.SpinboxCMMCount.configure(buttonbackground="#d9d9d9")
        self.SpinboxCMMCount.configure(disabledforeground="#a3a3a3")
        self.SpinboxCMMCount.configure(foreground="black")
        self.SpinboxCMMCount.configure(highlightbackground="black")
        self.SpinboxCMMCount.configure(highlightcolor="black")
        self.SpinboxCMMCount.configure(insertbackground="black")
        self.SpinboxCMMCount.configure(selectbackground="#c4c4c4")
        self.SpinboxCMMCount.configure(selectforeground="black")
        self.SpinboxCMMCount.configure(textvariable=dataProcessHelper_support.corr_cmm_count)
        self.SpinboxCMMCount.configure(width=65)

        self.Label1 = tk.Label(self.FrameCorr)
        self.Label1.place(relx=0.026, rely=0.551, height=23, width=38)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''CMM''')

        self.SpinboxCMMDataCount = tk.Spinbox(self.FrameCorr, from_=1.0, to=30.0)
        self.SpinboxCMMDataCount.place(relx=0.078, rely=0.493, relheight=0.061
                , relwidth=0.169)
        self.SpinboxCMMDataCount.configure(activebackground="#f9f9f9")
        self.SpinboxCMMDataCount.configure(background="white")
        self.SpinboxCMMDataCount.configure(buttonbackground="#d9d9d9")
        self.SpinboxCMMDataCount.configure(disabledforeground="#a3a3a3")
        self.SpinboxCMMDataCount.configure(foreground="black")
        self.SpinboxCMMDataCount.configure(highlightbackground="black")
        self.SpinboxCMMDataCount.configure(highlightcolor="black")
        self.SpinboxCMMDataCount.configure(insertbackground="black")
        self.SpinboxCMMDataCount.configure(selectbackground="#c4c4c4")
        self.SpinboxCMMDataCount.configure(selectforeground="black")
        self.SpinboxCMMDataCount.configure(textvariable=dataProcessHelper_support.corr_data_count)


        self.Label1_3 = tk.Label(self.FrameCorr)
        self.Label1_3.place(relx=0.026, rely=0.232, height=23, width=38)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''corr''')

        self.TextCORR = tk.Text(self.FrameCorr)
        self.TextCORR.place(relx=0.26, rely=0.029, relheight=0.933
                , relwidth=0.712)
        self.TextCORR.configure(background="white")
        self.TextCORR.configure(font="TkTextFont")
        self.TextCORR.configure(foreground="black")
        self.TextCORR.configure(highlightbackground="#d9d9d9")
        self.TextCORR.configure(highlightcolor="black")
        self.TextCORR.configure(insertbackground="black")
        self.TextCORR.configure(selectbackground="#c4c4c4")
        self.TextCORR.configure(selectforeground="black")
        self.TextCORR.configure(width=274)
        self.TextCORR.configure(wrap='word')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.013, rely=0.283, relheight=0.092
                , relwidth=0.481)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(width=385)

        self.CheckbuttonGRR = tk.Checkbutton(self.TFrame1)
        self.CheckbuttonGRR.place(relx=0.208, rely=0.364, relheight=0.491
                , relwidth=0.216)
        self.CheckbuttonGRR.configure(activebackground="#d9d9d9")
        self.CheckbuttonGRR.configure(activeforeground="#000000")
        self.CheckbuttonGRR.configure(background="#d9d9d9")
        self.CheckbuttonGRR.configure(disabledforeground="#a3a3a3")
        self.CheckbuttonGRR.configure(foreground="#000000")
        self.CheckbuttonGRR.configure(highlightbackground="#d9d9d9")
        self.CheckbuttonGRR.configure(highlightcolor="black")
        self.CheckbuttonGRR.configure(justify='left')
        self.CheckbuttonGRR.configure(text='''GRR''')
        self.CheckbuttonGRR.configure(variable=dataProcessHelper_support.check_grr)


        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.5, rely=0.283, relheight=0.092, relwidth=0.481)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=385)

        self.CheckbuttonCMM = tk.Checkbutton(self.Frame1)
        self.CheckbuttonCMM.place(relx=0.078, rely=0.364, relheight=0.491
                , relwidth=0.171)
        self.CheckbuttonCMM.configure(activebackground="#d9d9d9")
        self.CheckbuttonCMM.configure(activeforeground="#000000")
        self.CheckbuttonCMM.configure(background="#d9d9d9")
        self.CheckbuttonCMM.configure(disabledforeground="#a3a3a3")
        self.CheckbuttonCMM.configure(foreground="#000000")
        self.CheckbuttonCMM.configure(highlightbackground="#d9d9d9")
        self.CheckbuttonCMM.configure(highlightcolor="black")
        self.CheckbuttonCMM.configure(justify='left')
        self.CheckbuttonCMM.configure(text='''CORR CMM''')
        self.CheckbuttonCMM.configure(variable=dataProcessHelper_support.check_cmm)
  

if __name__ == '__main__':
    vp_start_gui()





